package org.psjava.judgesubmit;

public enum SubmitStatusCode {
	SYSTEM_ERROR, NO_SUCH_PROBLEM, ACCEPTED, RUNTIME_ERROR, WRONG_ANSWER, TIME_LIMIT_EXCEED, MEMORY_LIMITE_EXCEED, OUTPUT_LIMIT_EXCEED, RESTRICTED_FUNCTION, COMPILE_ERROR, CAN_NOT_BE_JUDGED, NOT_AUTHENTICATED, OUT_OF_CONTEST_TIME, DELAYED, COMPILING, RUNNING, JUDGING, WAITING, UNKNOWN, PRESENTATION_ERROR,
}
